// Generated by CoffeeScript 1.4.0
(function() {
  var tightrope;

  tightrope = require('../');

  describe('tightrope', function() {
    return it('should return a simple hash', function() {
      return tightrope.test.should.equal('asd');
    });
  });

}).call(this);
